version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=nuktinov@gmail.com --password=37421er54@@lullaby registry.heroku.com
         docker tag aspnetapp registry.heroku.com/bloglullabyapi/web
         docker push registry.heroku.com/bloglullabyapi/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a bloglullabyapi